spring:
  application:
    port: 8080
  #数据源配置
  datasource:
    url: jdbc:mysql://rm-2ze32abbq3m7r48edbo.mysql.rds.aliyuncs.com:3306/daas_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: cxdbroot
    password: Cxbid@2020
    type: com.alibaba.druid.pool.DruidDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#     connection-test-query: SELECT 1
# activiti:
#    database-schema-update: true
#    # 开启历史库
#    db-history-used: true
#    history-level: audit
mybatis:
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#wxpay: 
#   keyStore: /usr/local/platform-pay
wxpay: 
   keyStore: F:\\cert/apiclient_cert.p12